# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Bắt đầu giai đoạn build..."
          # Lệnh để build ứng dụng của bạn, ví dụ: npm install hoặc mvn package

      - name: Test
        run: |
          echo "Bắt đầu giai đoạn kiểm tra..."
          # Lệnh để chạy các bài kiểm tra đơn vị, tích hợp hoặc kiểm tra hiệu năng

      - name: Deploy
        run: |
          echo "Bắt đầu giai đoạn triển khai..."
          # Lệnh để triển khai ứng dụng của bạn lên môi trường thực
          
      - name: Realease
        run: |
          echo "Bắt đầu giai đoạn build..."
          # Lệnh để triển khai ứng dụng của bạn lên môi trường thực
